---
# make sure that the Oracle instant client is installed

- name: install unzip
  apt:
    name: unzip
    state: present
    update_cache: yes
    cache_valid_time: "3600"

- name: install libaio1
  apt:
    name: libaio1
    state: present
    update_cache: yes
    cache_valid_time: "3600"

- name: install libaio-dev
  apt:
    name: libaio-dev
    state: present
    update_cache: yes
    cache_valid_time: "3600"

- name: make sure that the /opt/oracle directory exists
  file:
    path: /opt/oracle
    state: directory

- name: install the basiclite archive
  unarchive:
    src: oracle/instantclient-basiclite-linux.x64-19.6.0.0.0dbru.zip
    dest: /opt/oracle
    creates: /opt/oracle/instantclient_19_6/BASIC_LITE_README

- name: install the sdk archive
  unarchive:
    src: oracle/instantclient-sdk-linux.x64-19.6.0.0.0dbru.zip
    dest: /opt/oracle
    creates: /opt/oracle/instantclient_19_6/sdk

- name: setup oracle_home and ld_library_path in profile.d
  copy:
    src: oracle_home.sh
    dest: /etc/profile.d/oracle_home.sh
    mode: "0755"

- name: add ORACLE_HOME to /etc/environment
  lineinfile:
    dest: /etc/environment
    state: present
    line: 'ORACLE_HOME="/opt/oracle/instantclient_19_6"'

- name: add LD_LIBRARY_PATH to /etc/environment
  lineinfile:
    dest: /etc/environment
    state: present
    line: 'LD_LIBRARY_PATH="/opt/oracle/instantclient_19_6"'
